# ENV Variables
# TP_THEME=overseerr
# SSD=/volume1/data4k
# HDD=/volume1/dataHd
# DOCKER=/volume1/docker

version: "1.0"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - VERSION=public
      - PLEX_CLAIM=claim-94sC-hcCbJ_kcKHiSdSd
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:plex
      - TP_THEME=${TP_THEME}
    volumes:
      - ${DOCKER}/plex/_data:/config
      - ${SSD}/media4k:/media4k
      - ${HDD}/media:/media
      - ${SSD}:/data4k
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:prowlarr
      - TP_THEME=${TP_THEME}
    volumes:
      - ${DOCKER}/prowlarr/_data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:sonarr
      - TP_THEME=${TP_THEME}
    volumes:
      - ${DOCKER}/sonarr/_data:/config
      - ${HDD}:/data
      - ${HDD}/media/tv:/tv
      - ${SSD}:/data4k
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:radarr
      - TP_THEME=${TP_THEME}
    volumes:
      - ${DOCKER}/radarr/_data:/config
      - ${HDD}:/data
      - ${HDD}/media/movies:/movies
      - ${SSD}:/data4k
    ports:
      - 7878:7878
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:sabnzbd
      - TP_THEME=${TP_THEME}
    volumes:
      - ${DOCKER}/sabnzbd/_data:/config
      - ${HDD}/usenet:/data/usenet/
      - ${SSD}/usenet4k:/data4k/usenet4k/
      - ${SSD}/media4k:/media4k
    ports:
      - 8081:8080
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:qbittorrent
      - TP_THEME=${TP_THEME}
    volumes:
      - ${DOCKER}/qbittorrent/_data:/config
      - ${HDD}/torrents:/data/torrents/
      - ${SSD}/torrents4k:/data4k/torrents4k/
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:tautulli
      - TP_THEME=${TP_THEME}
    volumes:
      - ${DOCKER}/tautulli/_data:/config
    ports:
      - 8181:8181
    restart: unless-stopped
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:overseerr
      - TP_THEME=${TP_THEME}
    volumes:
      - ${DOCKER}/overseerr/_data:/config
    ports:
      - 5055:5055
    restart: unless-stopped
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER}/homarr/_data:/app/data/configs
      - ${DOCKER}/homarr/icons:/app/public/icons
      - ${DOCKER}/homarr/data:/data
    ports:
      - '7575:7575'
  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    restart: unless-stopped
    ports:
      - "5454:5454"
    volumes:
      - ${DOCKER}/notifiarr/_data:/config
      - ${DOCKER}/notifiarr/utmp:/var/run/utmp
      - ${DOCKER}/notifiarr/machine-id:/etc/machine-id
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
    restart: unless-stopped
#  sonarr4k:
#    image: lscr.io/linuxserver/sonarr:develop
#    container_name: sonarr4k
#    environment:
#      - PUID=1027
#      - PGID=100
#      - TZ=Etc/UTC
#      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:sonarr
#      - TP_THEME=${TP_THEME}
#      - TP_ADDON=sonarr-4k-logo
#    volumes:
#      - ${DOCKER}/sonarr4k/_data:/config
#      - ${SSD}:/data4k
#      - ${SSD}/media4k/tv4k:/tv
#    ports:
#      - 8990:8989
#    restart: unless-stopped
#  radarr4k:
#    image: lscr.io/linuxserver/radarr:latest
#    container_name: radarr4k
#    environment:
#      - PUID=1027
#      - PGID=100
#      - TZ=Etc/UTC
#      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:radarr
#      - TP_THEME=${TP_THEME}
#      - TP_ADDON=radarr-4k-logo
#    volumes:
#      - ${DOCKER}/radarr4k/_data:/config
#      - ${SSD}:/data4k
#      - ${SSD}/media4k/movies4k:/movies
#    ports:
#      - 7879:7878
#    restart: unless-stopped
