version: "1.0"
volumes:
  plex:
  prowlarr:
  sonarr:
  radarr:
  lidarr:
  sabnzbd:
  qbittorrent:
  tautulli:
  overseerr:
  homarr:
  nginx-proxy-manager:
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - VERSION=public
      - PLEX_CLAIM=claim-94sC-hcCbJ_kcKHiSdSd
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:plex
      - TP_THEME=${TP_THEME}
    volumes:
      - plex:/config
      - /volume2/media/tv:/tv
      - /volume2/media/movies:/movies
      - /volume2/media/music:/music
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:prowlarr
      - TP_THEME=${TP_THEME}
    volumes:
      - prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:sonarr
      - TP_THEME=${TP_THEME}
    volumes:
      - sonarr:/config
      - /volume2/media/tv:/tv
      - /volume1/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:radarr
      - TP_THEME=${TP_THEME}
    volumes:
      - radarr:/config
      - /volume2/media/movies:/movies
      - /volume1/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:lidarr
      - TP_THEME=${TP_THEME}
    volumes:
      - lidarr:/config
      - /volume2/media/music:/music
      - /volume1/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:sabnzbd
      - TP_THEME=${TP_THEME}
    volumes:
      - sabnzbd:/config
      - /volume1/downloads:/downloads
    ports:
      - 8081:8080
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:qbittorrent
      - TP_THEME=${TP_THEME}
    volumes:
      - qbittorrent:/config
      - /volume1/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:tautulli
      - TP_THEME=${TP_THEME}
    volumes:
      - tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1027
      - PGID=100
      - TZ=Etc/UTC
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:overseerr
      - TP_THEME=${TP_THEME}
    volumes:
      - overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - homarr:/app/data/configs
      - /volume1/docker/homarr/icons:/app/public/icons
      - /volume1/docker/homarr/data:/data
    ports:
      - '7575:7575'
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '85:80'
      - '83:81'
      - '446:443'
    volumes:
      - nginx-proxy-manager:/data
      - /volume1/letsencrypt:/etc/letsencrypt
